#!/bin/env lua

-- a simple command line program for packing and unpacking res files
-- stage 1: simply list the contents

package.path = "../?/init.lua;"..package.path

require "res"

function main(filename)
	local rf = res.open(filename)
	assert(rf)
	
	print('%s: %d chunks' % { filename, rf.count })
	print('Comment: "%s"' % rf.comment:gsub('\n', '\\n'))
	
	print("   ID              type       size")
	for id,chunk in ipairs(rf) do
		printf("%5d  %16s  %8d%s%s\n",
			chunk.id,
			res.typename(chunk.type),
			chunk.size,
			chunk.compressed and " (compressed %d)" % chunk.packsize or "",
			chunk.nested and " (directory)" or ""
		)
		printf("\t%s\n", ("%q" % chunk.content):sub(1,40))
	end
end

do return main(...) end

